Config = {}

Config.fountain = {
    { coords = vector3(182.3146, -978.4347, 29.4885), radius = 10.0, debug = false},
    { coords = vector3(177.2334, -970.1216, 29.4605), radius = 10.0, debug = false},
    { coords = vector3(178.5560, -984.8797, 29.4605), radius = 10.0, debug = false}
}

Config.fortunetelling = {
    'You will find love when you least expect it.',
    'A great opportunity is just around the corner.',
    'Beware of unexpected surprises today.',
    'Someone close to you will soon reveal a secret.',
    'A journey you take will change your life forever.',
    'You will soon encounter an old friend from your past.',
    'Fortune favors the bold—take a risk this week.',
    'Your hard work will soon pay off in unexpected ways.',
    'A challenge lies ahead, but you have the strength to overcome it.',
    'An important decision will lead to great rewards.',
    'You will discover something valuable in a place you least expect.',
    'A new hobby will bring you joy and fulfillment.',
    'Expect a message that will bring you good news.',
    'Your patience will soon be rewarded in ways you can’t imagine.',
    'Someone will soon offer you the help you didn’t know you needed.',
    'You will soon receive a gift that you didn’t expect.',
    'A close family member will offer you valuable advice.',
    'You will soon meet someone who will change your perspective.',
    'A sudden twist of fate will lead you to success.',
    'Be mindful of your health—take time to relax.',
    'Something you have lost will soon be returned to you.',
    'Your creativity will open doors to new opportunities.',
    'Unexpected wealth will come your way within the next month.',
    'Beware of someone who seems too good to be true.',
    'A past mistake will soon lead to future success.',
    'Trust your instincts, they will guide you to the right path.',
    'A surprise event will make this week unforgettable.',
    'Someone from your past will reach out with good news.',
    'Your dreams will soon reveal hidden truths.',
    'An adventure awaits you in the near future.',
    'A change in your environment will bring you peace.',
    'An important meeting will lead to great opportunities.',
    'You will soon be faced with a tough choice, but you will make the right one.',
    'Someone is keeping a secret that will soon be revealed.',
    'A time of transformation is ahead—embrace the changes.',
    'Your reputation will soon be enhanced by your hard work.',
    'A quiet moment of reflection will bring you clarity.',
    'A project you’ve been working on will soon bear fruit.',
    'Your persistence will lead to a breakthrough.',
    'A pleasant surprise will make you smile.',
    'Your intuition will guide you toward a big decision.',
    'A new connection will lead to exciting possibilities.',
    'Expect to receive help when you need it most.',
    'Good fortune is following you, but don’t be afraid to take action.',
    'You will soon discover a hidden talent that will bring you joy.',
    'An unexpected event will lead you to a long-term goal.',
    'A bold move will lead to great success.',
    'You will soon have the opportunity to travel to a faraway place.',
    'A moment of clarity will bring you closer to your dreams.',
    'A new beginning is on the horizon—embrace it with open arms.',
    'The stars are aligning in your favor—trust the timing.',
    'A long-awaited decision will finally be made.',
    'Your efforts are being noticed—keep up the good work.',
    'Someone will offer you a piece of advice that will change your life.',
    'A big change in your personal life will lead to greater happiness.',
    'Your future is bright, filled with opportunities—grab them!',
    'Take time for yourself—you deserve it more than you realize.'
}
